# Generated by Django 3.0.7 on 2021-02-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jugadorLOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('cuenta', models.CharField(default='No', max_length=100)),
                ('twitch', models.CharField(default='No', max_length=1000)),
                ('twitter', models.CharField(default='No', max_length=1000)),
                ('link', models.CharField(default='No', max_length=1000)),
                ('rank', models.IntegerField(default=0)),
                ('summonerID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='jugadorMundial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='No', max_length=100)),
                ('LPs', models.IntegerField(default=0)),
                ('summonerID', models.CharField(default='No', max_length=100)),
                ('semana1Fates', models.IntegerField(default=0)),
                ('semana2Fates', models.IntegerField(default=0)),
                ('semana3Fates', models.IntegerField(default=0)),
                ('puntosMundial', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='jugadorTFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='No', max_length=100)),
                ('cuenta', models.CharField(default='No', max_length=100)),
                ('twitch', models.CharField(default='No', max_length=1000)),
                ('twitter', models.CharField(default='No', max_length=1000)),
                ('link', models.CharField(default='No', max_length=1000)),
                ('tier', models.CharField(default='', max_length=100)),
                ('division', models.CharField(default='', max_length=1000)),
                ('LPs', models.IntegerField(default=0)),
                ('summonerID', models.CharField(default='No', max_length=100)),
                ('semana1', models.IntegerField(default=0)),
                ('semana2', models.IntegerField(default=0)),
                ('semana3', models.IntegerField(default=0)),
                ('semana1Fates', models.IntegerField(default=0)),
                ('semana2Fates', models.IntegerField(default=0)),
                ('semana3Fates', models.IntegerField(default=0)),
                ('puntosMundial', models.IntegerField(default=0)),
                ('partidasJugadas', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('winrate', models.FloatField(default=0)),
            ],
        ),
    ]
