# Generated by Django 3.0.7 on 2021-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadormundial',
            name='español',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugadormundial',
            name='smurf',
            field=models.IntegerField(default=0),
        ),
    ]
