# Generated by Django 3.0.7 on 2021-02-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0002_auto_20210222_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadormundial',
            old_name='español',
            new_name='diferencia',
        ),
        migrations.RemoveField(
            model_name='jugadormundial',
            name='smurf',
        ),
    ]
