# Generated by Django 3.0.7 on 2021-03-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0004_jugadorrusia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadorrusia',
            name='ordenliga',
            field=models.IntegerField(default=0),
        ),
    ]
