# Generated by Django 3.0.7 on 2021-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0005_jugadorrusia_ordenliga'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadorrusia',
            name='equipo',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
