# Generated by Django 3.0.7 on 2021-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0006_jugadorrusia_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipoLatam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitan', models.CharField(max_length=100)),
                ('LPs', models.IntegerField(default=0)),
            ],
        ),
    ]
