# Generated by Django 3.0.7 on 2021-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0011_auto_20210614_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='puntosMundialReckoning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugadortft',
            name='semana1Reckoning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugadortft',
            name='semana2Reckoning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugadortft',
            name='semana3Reckoning',
            field=models.IntegerField(default=0),
        ),
    ]
