# Generated by Django 3.0.7 on 2021-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0013_jugadorhyperroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugadorPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('equipo', models.CharField(default='No', max_length=100)),
                ('twitch', models.CharField(default='No', max_length=1000)),
                ('twitter', models.CharField(default='No', max_length=1000)),
                ('coach', models.CharField(default='No', max_length=1000)),
                ('twitterCoach', models.CharField(default='No', max_length=100)),
            ],
        ),
    ]
