# Generated by Django 3.0.7 on 2021-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0014_jugadorpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadorpokemon',
            name='idtwitch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugadorpokemon',
            name='online',
            field=models.CharField(default='No', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadorpokemon',
            name='twitchname',
            field=models.CharField(default='No', max_length=1000),
        ),
    ]
