# Generated by Django 3.0.7 on 2021-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0015_auto_20210706_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='dentroLista',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
