# Generated by Django 3.2.12 on 2022-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0017_jugadorlor_dentrolista'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyDataJugadoresTFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='No', max_length=100)),
                ('set6Data', models.JSONField()),
            ],
        ),
    ]
