# Generated by Django 3.2.12 on 2022-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0020_studydatajugadorestft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studyDataJugadoresTFT',
        ),
    ]
