# Generated by Django 3.2.12 on 2022-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0023_jugadortft_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='twitchname',
            field=models.CharField(default='No', max_length=1000),
        ),
    ]
