# Generated by Django 3.2.13 on 2022-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0024_jugadortft_twitchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
