# Generated by Django 3.2.13 on 2022-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0025_studydatajugadorestft_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='top1EspJugadoresTFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='No', max_length=100)),
                ('set', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
