# Generated by Django 3.2.13 on 2022-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0027_top1espjugadorestft_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top1espjugadorestft',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='top1espjugadorestft',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
