# Generated by Django 3.2.13 on 2022-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0028_auto_20220421_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top1espjugadorestft',
            name='set',
            field=models.FloatField(default=0),
        ),
    ]
