# Generated by Django 3.2.13 on 2022-04-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0029_alter_top1espjugadorestft_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='LPsParche',
            field=models.IntegerField(default=0),
        ),
    ]
