# Generated by Django 3.2.13 on 2022-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0030_studydatajugadorestft_lpsparche'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='picoLPs',
            field=models.IntegerField(default=0),
        ),
    ]
