# Generated by Django 3.2.13 on 2022-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0031_jugadortft_picolps'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='puuid',
            field=models.CharField(default='No', max_length=1000),
        ),
    ]
