# Generated by Django 3.2.13 on 2022-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0032_jugadortft_puuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='actualizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='ultimoGame',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
