# Generated by Django 3.2.13 on 2022-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0033_auto_20220501_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='ultimoGame',
        ),
        migrations.AddField(
            model_name='jugadortft',
            name='actualizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jugadortft',
            name='ultimoGame',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
