# Generated by Django 3.2.13 on 2022-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0035_studydatajugadorestft_set7data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top1espjugadorestft',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='top1espjugadorestft',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
