# Generated by Django 3.2.13 on 2022-06-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0036_auto_20220608_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='set7Data',
        ),
    ]
