# Generated by Django 3.2.13 on 2022-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0038_studydatajugadorestft_set7data'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosCompetitivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField()),
                ('set', models.FloatField()),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
    ]
