# Generated by Django 3.2.13 on 2022-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0040_auto_20220907_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydatajugadorestft',
            name='set6Data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='studydatajugadorestft',
            name='set7BData',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='studydatajugadorestft',
            name='set7BELO',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='studydatajugadorestft',
            name='set7Data',
            field=models.JSONField(null=True),
        ),
    ]
