# Generated by Django 3.2.13 on 2022-12-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0041_auto_20220908_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='set8Data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='set8ELO',
            field=models.JSONField(null=True),
        ),
    ]
