# Generated by Django 3.2.13 on 2022-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0044_top1eujugadorestft'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='topEUW',
            field=models.IntegerField(default=0),
        ),
    ]
