# Generated by Django 4.1.5 on 2023-01-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0045_jugadortft_topeuw'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortft',
            name='topESP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='jugadorTFT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listaTFT.jugadortft'),
        ),
    ]
