# Generated by Django 4.1.5 on 2023-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0046_jugadortft_topesp_studydatajugadorestft_jugadortft'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugadorEuropeoFates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='No', max_length=100)),
                ('LPs', models.IntegerField(default=0)),
                ('summonerID', models.CharField(default='No', max_length=100)),
                ('semana1Fates', models.IntegerField(default=0)),
                ('semana2Fates', models.IntegerField(default=0)),
                ('semana3Fates', models.IntegerField(default=0)),
                ('puntosMundial', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='equipoLatam',
        ),
        migrations.DeleteModel(
            name='jugadorHyperroll',
        ),
        migrations.DeleteModel(
            name='jugadorLOR',
        ),
        migrations.DeleteModel(
            name='jugadorMundial',
        ),
        migrations.DeleteModel(
            name='jugadorPokemon',
        ),
        migrations.DeleteModel(
            name='jugadorRusia',
        ),
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='set6Data',
        ),
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='set7BData',
        ),
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='set7BELO',
        ),
        migrations.RemoveField(
            model_name='studydatajugadorestft',
            name='set7Data',
        ),
    ]
