# Generated by Django 4.1.5 on 2023-03-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTFT', '0047_jugadoreuropeofates_delete_equipolatam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydatajugadorestft',
            name='set8BELO',
            field=models.JSONField(null=True),
        ),
    ]
